name: Check code style

on:
  [ push, pull_request ]

jobs:

  Check_code_style:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [ 3.10 ]

    steps:

      - name: Set up Git repository
        uses: actions/checkout@v2


      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}


      - name: Install dev-requirements
        run: |
          pip install --no-cache-dir -r requirements.txt

      - name: Run flake8
        run: |
          flake8 .